config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: 'pages#index'

  get 'pages/index'
  get 'pages/test', as: 'test'

  post 'payments/stripe', to: 'payments#stripe'
  get 'payments/stripe', to: 'payments#stripe', as: 'payments'

  resources :climb_classes,
            :climb_schedules,
            :climb_tags,
            :climbs,
            :climber_educations,
            :climber_experiences,
            :climb_leader_profiles,
            :educations,
            :general_dates,
            :routes,
            :specific_dates,
            :user_roles

post 'users/start_subscription', to: 'users#start_subscription', as: 'subscribe'
post 'users/end_autorenew', to: 'users#end_autorenew', as: 'end_autorenew'
post 'users/restart_autorenew', to: 'users#restart_autorenew', as: 'restart_autorenew'

resources :users do
  resources :climbs do
    resources :climb_apps
  end
end

resources :mountains do
  resources :climbs
end

resources :users do
  resources :climb_apps
  resources :climber_profiles
end

end

app/models/mountain.rb
class Mountain < ActiveRecord::Base
  has_many :routes


  def map_zoom
    if !elevation_feet.nil?
      elevation = elevation_feet.gsub(",","").to_i
    else
      elevation = 0
    end

    if elevation < 8000
      level = 14
    else
      level = 12
    end
    return level
  end

  def latitude_offset
    offset = 0
    if map_zoom == 14
      offset = 0.0035
    elsif map_zoom == 12
      offset = 0.015
    end
    return offset
  end

  def longitude_offset
    offset = 0
    if map_zoom == 14
      offset = 0.014
    elsif map_zoom == 12
      offset = 0.055
    end
    return offset
  end


  def route_types
    types = []
    routes.each do |route|
      types << route.typical_gear
    end
    return types.uniq
  end

  def route_headers
    headers = []
    type_list = route_types
    if type_list.include? "rock"
      headers << "ROCK"
    end

    if type_list.include? "snow"
      headers << "SNOW"
    end

    if type_list.include? "rock and snow"
      headers = ["ROCK", "SNOW"]
    end

    return headers
  end

  def class_ordered_routes
    routes.order("climb_class_id")
  end

  def driving_text
    text = ""
    if !driving_distance.nil? && !driving_time.nil?
      text = "#{driving_distance} miles, #{driving_time} hours from Portland"
    elsif !driving_distance.nil?
      text = "#{driving_distance} miles from Portland"
    elsif !driving_time.nil?
      text = "#{driving_time} miles from Portland"
    end
    return text
  end

  def elevation_text
    text = ""
    if !elevation_feet.nil?
      number = elevation_feet.to_s.insert(-4,",")
      text = "#{number} feet"
    end
    return text
  end


  # def geo_json()
  #   geo_json = []
  #   geo_json << {
  #     type: "Feature",
  #     geometry: {
  #       type: "Point",
  #       coordinates: [mountain.longitude, mountain.latitude]
  #     },
  #     properties: {
  #       title: mountain.name,
  #       :"marker-color" => "#FFFFFF",
  #       :"marker-symbol" => "circle",
  #       :"marker-size" => "medium",
  #     }
  #   }
  # end
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  before_action :set_mountain, only: [:show, :edit, :update, :destroy]
  before_filter :set_search

  # GET /mountains
  # GET /mountains.json
  def index
    if !params[:commit].nil? && params[:commit].downcase == "search"
      if !params[:q].blank?
        @results = Mountain.search(params[:q])
      else
        @results = Mountain.search({:id_eq => 0})
      end

      @mountains = @results.result

    else
      @mountains = Mountain.all
    end

  end

  # GET /mountains/1
  # GET /mountains/1.json
  def show
    @routes = @mountain.routes.order("name")
  end

  # GET /mountains/new
  def new
    @mountain = Mountain.new
  end

  # GET /mountains/1/edit
  def edit
  end

  # POST /mountains
  # POST /mountains.json
  def create
    @mountain = Mountain.new(mountain_params)

    respond_to do |format|
      if @mountain.save
        format.html { redirect_to @mountain, notice: 'Mountain was successfully created.' }
        format.json { render :show, status: :created, location: @mountain }
      else
        format.html { render :new }
        format.json { render json: @mountain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mountains/1
  # PATCH/PUT /mountains/1.json
  def update
    respond_to do |format|
      if @mountain.update(mountain_params)
        format.html { redirect_to @mountain, notice: 'Mountain was successfully updated.' }
        format.json { render :show, status: :ok, location: @mountain }
      else
        format.html { render :edit }
        format.json { render json: @mountain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mountains/1
  # DELETE /mountains/1.json
  def destroy
    @mountain.destroy
    respond_to do |format|
      format.html { redirect_to mountains_url, notice: 'Mountain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mountain
      @mountain = Mountain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mountain_params
      params.fetch(:mountain, {})
    end

    # Attempted to used named urls, but stopped. Function currently not in use:
    def snake_name
      @mountain.name.gsub(/./,'').gsub(/ /,'_').downcase
    end
end

app/helpers/mountains_helper.rb
module MountainsHelper
end

app/views/mountains/_form.html.erb
<%= form_for(@mountain) do |f| %>
  <% if @mountain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mountain.errors.count, "error") %> prohibited this mountain from being saved:</h2>

      <ul>
      <% @mountain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mountains/edit.html.erb
<h1>Editing Mountain</h1>

<%= render 'form' %>

<%= link_to 'Show', @mountain %> |
<%= link_to 'Back', mountains_path %>

app/views/mountains/index.html.erb
<head>
  <% title("Mountains") %>
</head>

<div class="nav-spacing"></div>

<h4 id="notice" class="f3"><%= notice %></h4>

<div class="f5 container six columns offset-by-three">

  <div id="mountain_search" class="search f1">
    <%= search_form_for @search_mountain do |f| %>
      <%= f.search_field :name_or_state_or_country_cont, placeholder: "Search Mountains by Name or Location"%>
      <%= f.submit "", class: "search-button", value: "search"%>
    <% end %>
  </div>

  <table class="mountain-list">
    <thead>
        <td><h4 class="f3">Peak</h4></td>
        <td><h4 class="f3">Location</h4></td>
    </thead>

    <tbody>
      <% @mountains.each do |mountain| %>
        <tr>
          <td><h5 class="f2"><%= link_to mountain.name, mountain %></h5></td>
          <td><h5 class="f2"><%= mountain.state %><%= mountain.country != "United States" ? ", #{mountain.country}" : "" %></h5></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

<script>
$("#mountain_search input").keypress(function(event) {
    if (event.which == 13) {
        event.preventDefault();
        $("#mountain_search").submit([name: "commit", value: "search"]);
    }
});
</script>

app/views/mountains/new.html.erb
<h1>New Mountain</h1>

<%= render 'form' %>

<%= link_to 'Back', mountains_path %>

app/views/mountains/show.html.erb
<head>
  <% title(@mountain.name) %>
</head>

<h4 id="notice" class="f3"><%= notice %></h4>


<div id='map'></div>

<div class="all-but-header">
  <section class="mountain-description-overlay eleven columns offset-by-zero">
    <section class="mountain-stats">
      <div class="mountain-text">
        <h1 class="f3"><%= @mountain.name %></h1>
        <h4 class="f2"><%= @mountain.state %>, <%= @mountain.country %></h5>
        <% if @mountain.driving_text != "" %>
          <h5 class="f1"><%= @mountain.driving_text %></h5>
        <% end %>

        <table class="mountain-data f1">
          <tr>
            <td>COORDINATES</td>
            <td><%= link_to "#{@mountain.latitude}, #{@mountain.longitude}", @mountain.google_maps_url, { target: '_blank' }  %></td>
          </tr>
          <tr>
            <td>ELEVATION</td>
            <td><%= @mountain.elevation_text %></td>
          </tr>
          <tr>
            <td>GLACIATED</td>
            <td><%= @mountain.glaciated ? "Yes" : "No" %></td>
          </tr>
        </table>

        <h5 class="f1"><%= link_to "Summit Post", @mountain.summit_post_url, { target: '_blank' } %></h5>
      </div>

      <table class="mountain-details f2">
        <tr>
          <th>ROUTE</th>
          <th>GAIN</th>
          <% @mountain.route_headers.each do |header| %>
            <th><%= header %></th>
          <% end %>

        </tr>
      </table>
    </section>
    <div class="overflow-scroll">
      <table class="mountain-details f2">

      <% @routes.each do |route| %>
        <tr>
          <td>
            <div class="climb-class-circle <%= route.climb_class.code %>-color"><%= route.climb_class.code %></div>
            <%= route.name %>
          </td>
          <td><%= !route.elevation_gain.nil? ? "#{number_with_delimiter(route.elevation_gain)} ft" : "" %></td>

          <% if @mountain.route_headers.length == 2 %>
            <td><%= route.rock_class_text %></td>
            <td><%= route.snow_angle_text %></td>
          <% elsif route.typical_gear == "snow" %>
            <td><%= route.snow_angle_text %></td>
          <% elsif route.typical_gear == "rock" %>
            <td><%= route.rock_class_text %></td>
          <% end %>
        </tr>
        <% end %>
      </div>
    </table>
  </section>
</div>




<!-- JAVASCRIPT FOR MAP LOAD. Should be moved to JS files? -->

<script>
// Unable to use dotenv in this file? Replacing with ENV['MAPBOX_PUBLIC_TOKEN'] fails.
mapboxgl.accessToken = 'pk.eyJ1IjoiY2xpbWJ3aXRobWF6YW1hcyIsImEiOiJjaXh5ODdpengwMDRuMndxdW9zNHJqbjNyIn0.ECqrLVMXr5JQ9t1fRdo5lQ';

var zoom = <%= @mountain.map_zoom %>;
var latitude_offset = 0;
var longitude_offset = 0;


// On a horizontal screen, leave longitude offset at 0, change latitude offset
if (window.matchMedia("(orientation: landscape)").matches) {
  longitude_offset = <%= @mountain.longitude_offset %>
}

if (window.matchMedia("(orientation: portrait)").matches) {
  latitude_offset = <%= @mountain.latitude_offset %>
}

var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/climbwithmazamas/cixyblwnf00202smnf4yywv4g', //stylesheet location
    center: [<%= @mountain.longitude %> + longitude_offset, <%= @mountain.latitude %> - latitude_offset], // starting position
    zoom: zoom // starting zoom
});

</script>