config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: 'pages#index'

  get 'pages/index'
  get 'pages/test', as: 'test'

  post 'payments/stripe', to: 'payments#stripe'
  get 'payments/stripe', to: 'payments#stripe', as: 'payments'

  resources :climb_classes,
            :climb_schedules,
            :climb_tags,
            :climbs,
            :climber_educations,
            :climber_experiences,
            :climb_leader_profiles,
            :educations,
            :general_dates,
            :routes,
            :specific_dates,
            :user_roles

post 'users/start_subscription', to: 'users#start_subscription', as: 'subscribe'
post 'users/end_autorenew', to: 'users#end_autorenew', as: 'end_autorenew'
post 'users/restart_autorenew', to: 'users#restart_autorenew', as: 'restart_autorenew'

resources :users do
  resources :climbs do
    resources :climb_apps
  end
end

resources :mountains do
  resources :climbs
end

resources :users do
  resources :climb_apps
  resources :climber_profiles
end

end

app/models/climb.rb
class Climb < ActiveRecord::Base
  has_many                  :climb_apps
  has_and_belongs_to_many   :educations
  has_and_belongs_to_many   :climb_tags
  belongs_to                :climb_schedule
  has_one                   :specific_date
  has_one                   :general_date
  belongs_to                :route
  belongs_to                :leader_1,    class_name: 'User'
  belongs_to                :leader_2,    class_name: 'User'
  belongs_to                :assistant_2, class_name: 'User'
  belongs_to                :assistant_1, class_name: 'User'

  has_one       :mountain,      through: :route
  has_one       :climb_class,   through: :route
  has_one       :climb_class,   through: :route


  def spots_available
    occupied = climb_apps.where(climb_app_status: 'accepted').length

    !leader_1.nil? ? occupied += 1 : nil
    !leader_2.nil? ? occupied += 1 : nil
    !assistant_1.nil? ? occupied += 1 : nil
    !assistant_2.nil? ? occupied += 1 : nil

    available = party_size - occupied
  end

  def date_text
    text = ""
    if !specific_date.nil?
      if specific_date.date_leave_town.strftime('%m-%d-%Y') == specific_date.date_return_town.strftime('%m-%d-%Y')
        text = specific_date.date_leave_town.strftime('%m-%d-%Y')
      else
        text = "#{specific_date.date_leave_town.strftime('%m-%d-%Y')} to #{specific_date.date_return_town.strftime('%m-%d-%Y')}"
      end
    else
      text = "#{general_date.month} #{general_date.year}"
    end
    return text
  end
end

app/controllers/climbs_controller.rb
class ClimbsController < ApplicationController
  before_action :set_climb, only: [:show, :edit, :update, :destroy]
  before_filter :set_search


  # GET /climbs
  # GET /climbs.json
  def index
    if !params[:commit].nil? && params[:commit].downcase == "search"
      if !params[:q].blank?
        @results = Climb.search(params[:q])
        puts @results.result
      else
        @results = Climb.search({:id_eq => 0})
      end

      @climbs = @results.result

    else
      @climbs = Climb.paginate(:page => params[:page], :per_page => 10)
    end

    respond_to do |format|
      format.html
      format.js
      # format.json { render json: # some JSON data }
    end
  end

  # GET /climbs/1
  # GET /climbs/1.json
  def show
  end

  # GET /climbs/new
  def new
    @climb = Climb.new
  end

  # GET /climbs/1/edit
  def edit
  end

  # POST /climbs
  # POST /climbs.json
  def create
    @climb = Climb.new(climb_params)

    respond_to do |format|
      if @climb.save
        format.html { redirect_to @climb, notice: 'Climb was successfully created.' }
        format.json { render :show, status: :created, location: @climb }
      else
        format.html { render :new }
        format.json { render json: @climb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /climbs/1
  # PATCH/PUT /climbs/1.json
  def update
    respond_to do |format|
      if @climb.update(climb_params)
        format.html { redirect_to @climb, notice: 'Climb was successfully updated.' }
        format.json { render :show, status: :ok, location: @climb }
      else
        format.html { render :edit }
        format.json { render json: @climb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climbs/1
  # DELETE /climbs/1.json
  def destroy
    @climb.destroy
    respond_to do |format|
      format.html { redirect_to climbs_url, notice: 'Climb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_climb
      @climb = Climb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def climb_params
      params.fetch(:climb, {})
    end

    def check_status
      if spots_available <= 0 && climb_stats != "closed"
        climb_status = "waitlist"
      end
    end
end

app/helpers/climbs_helper.rb
module ClimbsHelper
end

app/views/climbs/_climb.html.erb
<section class="climb-overview">
  <h2><%= climb.mountain.name %></h2>
  <h3><%= climb.route.name %></h3>
  <p><%= climb.climb_class.code %></p>
  <p><%= climb.climb_status %></p>
  <p><%= climb.party_size %></p>
  <p><%= climb.leader_1.first_name %> <%= climb.leader_1.last_name %></p>
  <button><%= link_to 'Details', climb %></button>
</section>

app/views/climbs/_form.html.erb
<%= form_for(@climb) do |f| %>
  <% if @climb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@climb.errors.count, "error") %> prohibited this climb from being saved:</h2>

      <ul>
      <% @climb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/climbs/edit.html.erb
<h1>Editing Climb</h1>

<%= render 'form' %>

<%= link_to 'Show', @climb %> |
<%= link_to 'Back', climbs_path %>

app/views/climbs/index.html.erb
<head>
  <% title("Climbs") %>
</head>

<div class="nav-spacing"></div>

<h4 id="notice" class="f3"><%= notice %></h4>

<div class="f5 container six columns offset-by-three">

  <div class="search f1">
    <%= search_form_for @search_climb do |f| %>
      <%= f.search_field :description_cont, placeholder: "Search Climbs"%>
      <%= f.submit "", class: "search-button"%>
    <% end %>
  </div>

  <section id="all-climbs">
    <% @climbs.each do |climb| %>
      <section class="one-climb">
        <div class="always-visible">

          <div class="climb-class-circle-large <%= climb.route.climb_class.code %>-color"><h5 class=f2><%= climb.route.climb_class.code %></h5></div>

          <div class="climb-mountain-route">
            <h4 class="f2"><%= link_to climb.mountain.name, climb.mountain %> — <%= climb.climb_status.upcase %></h5>
            <h5 class="f2"><%= climb.route.name %> Route with <%= climb.leader_1.first_name%> <%= climb.leader_1.last_name %></h5>
            <p class="f1"><%= climb.date_text %></p>
          </div>

          <div class="status-toggle">
            <h5 class="f2 toggle"><i class="fa fa-angle-down fa-2x" aria-hidden="true"></i></h5>
          </div>

        </div>

        <div class="hidden-until">

          <% if !climb.mountain.latitude.nil? && !climb.mountain.longitude.nil?  %>
            <div class="static-map-container">
              <img src='https://api.mapbox.com/v4/mapbox.light/pin-m-circle+3343A1(<%= climb.mountain.longitude %>,<%= climb.mountain.latitude %>)/<%= climb.mountain.longitude %>,<%= climb.mountain.latitude %>,5/320x550@2x.png?access_token=pk.eyJ1IjoiY2xpbWJ3aXRobWF6YW1hcyIsImEiOiJjaXh5ODdpengwMDRuMndxdW9zNHJqbjNyIn0.ECqrLVMXr5JQ9t1fRdo5lQ' alt='Map of <%= climb.mountain.name %>' class="static-map">
            </div>
          <% else %>
            <div class="static-map-container">
              <img src='https://placehold.it/320x550'>
            </div>
          <% end %>

          <div class="details">
            <table class="mountain-data f1">
              <% if !climb.leader_1.nil? %>
              <tr>
                <td>LEADER</td>
                <td><%= climb.leader_1.first_name%> <%= climb.leader_1.last_name %></td>
              </tr>
              <% end %>

              <% if !climb.leader_2.nil? %>
              <tr>
                <td>LEADER</td>
                <td><%= climb.leader_2.first_name%> <%= climb.leader_2.last_name %></td>
              </tr>
              <% end %>

              <% if !climb.assistant_1.nil? %>
              <tr>
                <td>ASSISTANT</td>
                <td><%= climb.assistant_1.first_name%> <%= climb.assistant_1.last_name %></td>
              </tr>
              <% end %>

              <% if !climb.assistant_2.nil? %>
              <tr>
                <td>ASSISTANT</td>
                <td><%= climb.assistant_2.first_name%> <%= climb.assistant_2.last_name %></td>
              </tr>
              <% end %>

              <tr>
                <td>PARTY SIZE</td>
                <td><%= climb.party_size %></td>
              </tr>
              <tr>
                <td>SPOTS AVAILABLE</td>
                <td><%= climb.spots_available %></td>
              </tr>
              <tr>
                <td>ROCK CLASS</td>
                <td><%= climb.route.rock_class_text %></td>
              </tr>
              <tr>
                <td>SNOW ANGLE</td>
                <td><%= climb.route.snow_angle_text %></td>
              </tr>
              <tr>
                <td>GRAD PREFERENCES</td>
                <td><%= list(climb.educations, "abbreviation") %></td>
              </tr>
              <tr>
                <td>TAGS</td>
                <td><%= list(climb.climb_tags, "code") %></td>
              </tr>

              <% if !climb.specific_date.nil? %>
                <tr>
                  <td>LEAVE TOWN</td>
                  <td><%= climb.specific_date.date_leave_town.strftime('%m-%d-%Y') %></td>
                </tr>
                <tr>
                  <td>LEAVE TRAILHEAD</td>
                  <td><%= climb.specific_date.date_leave_trailhead.strftime('%m-%d-%Y') %></td>
                </tr>
                <tr>
                  <td>SUMMIT</td>
                  <td><%= climb.specific_date.date_summit.strftime('%m-%d-%Y') %></td>
                </tr>
                <tr>
                  <td>BACK TO TRAILHEAD</td>
                  <td><%= climb.specific_date.date_return_trailhead.strftime('%m-%d-%Y') %></td>
                </tr>
                <tr>
                  <td>BACK TO TOWN</td>
                  <td><%= climb.specific_date.date_return_town.strftime('%m-%d-%Y') %></td>
                </tr>

              <% elsif !climb.general_date.nil? %>
                <tr>
                  <td>WEATHER DEPENDENT</td>
                  <td><%= climb.general_date.month %> <%= climb.general_date.year %></td>
                </tr>
              <% end %>

              <tr>
                <td>LAST UPDATED</td>
                <td><%= climb.last_updated.strftime('%m-%d-%Y') %></td>
              </tr>
            </table>

            <%= form_for climb, url: { action: "create" }, method: "post" do |f| %>
              <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button profile-button f2"
                data-key="pk_test_uuP4f9lToS2cmYlc6RneOwqV"
                data-amount="2000"
                data-name="The Mazamas"
                data-description="Application for <%= climb.mountain.name %>"
                data-locale="auto"
                data-label="Apply to <%= climb.mountain.name %>"
                data-image="https://www.mazamasclimbs.org/assets/mazamas-logo-square-227a770fb59bffaac46635487b9d514dfb4401839766b04dfba02f06893214f3.jpg"
                data-email=<%= current_user.email %> >

              </script>
            <% end %>

          </div>
        </div>
      </section>
    <% end %>
  </section>

</div>




<script>
$("#route_search input").keypress(function(event) {
    if (event.which == 13) {
        event.preventDefault();
        $("#route_search").submit([name: "commit", value: "search"]);
    }
});
</script>

<script>
$(document).ready(function(){
  $(".toggle").click(function(event) {
    event.preventDefault();
    // console.log("you clicked me");
    // console.log($(this).parent().parent().parent());
    // console.log($(this).parent().parent().parent().find(".hidden-until"));
    var hidden_block = $(this).parent().parent().parent().find(".hidden-until");

    // console.log(hidden_block.css("display"));
    if (hidden_block.css("display") === "none" || hidden_block.css("display") === undefined) {
      $(this).html("<i class='fa fa-angle-down fa-2x fa-flip-vertical' aria-hidden='true'></i>");
      $(this).parent().parent().css("background-color", "#EEEEEE");
      hidden_block.css("display", "block");
    }
    else {
      $(this).html("<i class='fa fa-angle-down fa-2x' aria-hidden='true'></i>");
      $(this).parent().parent().css("background-color", "#FFFFFF");
      hidden_block.css("display", "none");
    }
  });
});
</script>

app/views/climbs/index.js.erb
$('#all-climbs').append('<%= j render @climbs %>');
<% if @climbs.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @climbs %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/climbs/new.html.erb
<h1>New Climb</h1>

<%= render 'form' %>

<%= link_to 'Back', climbs_path %>

app/views/climbs/show.html.erb
<h4 id="notice" class="f3"><%= notice %></h4>

<%= link_to 'Edit', edit_climb_path(@climb) %> |
<%= link_to 'Back', climbs_path %>