config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: 'pages#index'

  get 'pages/index'
  get 'pages/test', as: 'test'

  post 'payments/stripe', to: 'payments#stripe'
  get 'payments/stripe', to: 'payments#stripe', as: 'payments'

  resources :climb_classes,
            :climb_schedules,
            :climb_tags,
            :climbs,
            :climber_educations,
            :climber_experiences,
            :climb_leader_profiles,
            :educations,
            :general_dates,
            :routes,
            :specific_dates,
            :user_roles

post 'users/start_subscription', to: 'users#start_subscription', as: 'subscribe'
post 'users/end_autorenew', to: 'users#end_autorenew', as: 'end_autorenew'
post 'users/restart_autorenew', to: 'users#restart_autorenew', as: 'restart_autorenew'

resources :users do
  resources :climbs do
    resources :climb_apps
  end
end

resources :mountains do
  resources :climbs
end

resources :users do
  resources :climb_apps
  resources :climber_profiles
end

end

app/models/climber_profile.rb
class ClimberProfile < ActiveRecord::Base
  has_many :climber_experiences
  belongs_to :user
  has_many :climber_educations
end

app/controllers/climber_profiles_controller.rb
class ClimberProfilesController < ApplicationController
  before_action :set_climber_profile, only: [:show, :edit, :update, :destroy]

  # GET /climber_profiles
  # GET /climber_profiles.json
  def index
    @climber_profiles = ClimberProfile.all
  end

  # GET /climber_profiles/1
  # GET /climber_profiles/1.json
  def show
  end

  # GET /climber_profiles/new
  def new
    @climber_profile = ClimberProfile.new
  end

  # GET /climber_profiles/1/edit
  def edit
  end

  # POST /climber_profiles
  # POST /climber_profiles.json
  def create
    @climber_profile = ClimberProfile.new(climber_profile_params)

    respond_to do |format|
      if @climber_profile.save
        format.html { redirect_to @climber_profile, notice: 'Climber profile was successfully created.' }
        format.json { render :show, status: :created, location: @climber_profile }
      else
        format.html { render :new }
        format.json { render json: @climber_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /climber_profiles/1
  # PATCH/PUT /climber_profiles/1.json
  def update
    respond_to do |format|
      if @climber_profile.update(climber_profile_params)
        format.html { redirect_to @climber_profile, notice: 'Climber profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @climber_profile }
      else
        format.html { render :edit }
        format.json { render json: @climber_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climber_profiles/1
  # DELETE /climber_profiles/1.json
  def destroy
    @climber_profile.destroy
    respond_to do |format|
      format.html { redirect_to climber_profiles_url, notice: 'Climber profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_climber_profile
      @climber_profile = ClimberProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def climber_profile_params
      params.fetch(:climber_profile, {})
    end
end

app/helpers/climber_profiles_helper.rb
module ClimberProfilesHelper
end

app/views/climber_profiles/_form.html.erb
<%= form_for(@climber_profile) do |f| %>
  <% if @climber_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@climber_profile.errors.count, "error") %> prohibited this climber_profile from being saved:</h2>

      <ul>
      <% @climber_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/climber_profiles/edit.html.erb
<h1>Editing Climber Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @climber_profile %> |
<%= link_to 'Back', climber_profiles_path %>

app/views/climber_profiles/index.html.erb
<h4 id="notice" class="f3"><%= notice %></h4>

<h1>Listing Climber Profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @climber_profiles.each do |climber_profile| %>
      <tr>
        <td><%= link_to 'Show', climber_profile %></td>
        <td><%= link_to 'Edit', edit_climber_profile_path(climber_profile) %></td>
        <td><%= link_to 'Destroy', climber_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Climber profile', new_climber_profile_path %>

app/views/climber_profiles/new.html.erb
<h1>New Climber Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', climber_profiles_path %>

app/views/climber_profiles/show.html.erb
<head>
  <% title "Climb Resume" %>
</head>

<div class="nav-spacing"></div>
<div class="general-spacing"></div>

<div class="profile six columns offset-by-three">
  <h4 id="notice" class="f3"><%= notice %></h4>

  <div class="profile-header">
    <h4 class="f3">Climber Bio</h4>
    <%= button_to 'Edit', edit_user_climber_profile_path(current_user, @climber_profile), class: "profile-button f2" %>
  </div>

  <section class= "profile-table f2">
    <div>
      <h5>NAME</h5>
      <h5><%= @climber_profile.user.first_name %> <%= @climber_profile.user.last_name %></h5>
    </div>
    <div>
      <h5>BIO</h5>
      <h5><%= @climber_profile.bio %></h5>
    </div>
    <div>
      <h5>VOLUNTEER HISTORY</h5>
      <h5><%= @climber_profile.volunteer_history %></h5>
    </div>
    <div>
      <h5>PHYSICAL CONDITIONING</h5>
      <h5><%= @climber_profile.physical_conditioning %></h5>
    </div>
    <div>
      <h5>MEDICAL CONDITION</h5>
      <h5><%= @climber_profile.medical_condition %></h5>
    </div>
    <div>
      <h5>MEDICATION</h5>
      <h5><%= @climber_profile.medication %></h5>
    </div>

  <section class="half-spacing"></section>

  <div class="profile-header">
    <h4 class="f3">Climbing Resume</h4>
    <%= button_to 'Edit', edit_user_climber_profile_path(current_user, @climber_profile), class: "profile-button f2" %>
  </div>

  <section class="experience-table">
    <% @climber_profile.climber_experiences.order(:year).each do |climber_experience| %>
    <div>
      <% route = Route.find_by(name: climber_experience.route) %>
        <% if !route.nil? %>
          <h5><%= route.climb_class.code %></h5>
        <% end %>
      <h5><%= climber_experience.mountain %></h5>
      <h5><%= climber_experience.route %></h5>
      <h5><%= climber_experience.role %></h5>
      <h5><%= climber_experience.climb_leader %></h5>
      <h5><%= climber_experience.climb_type.capitalize %></h5>
      <h5><%= climber_experience.month.capitalize %></h5>
      <h5><%= climber_experience.year %></h5>
    </div>
    <% end %>
  </section>

  <section class="half-spacing"></section>

  <div class="profile-header">
    <h4 class="f3">Climbing Education</h4>
    <%= button_to 'Edit', edit_user_climber_profile_path(current_user, @climber_profile), class: "profile-button f2" %>
  </div>

  <section class="three-columns">
    <% @climber_profile.climber_educations.order(:year).each do |climber_education| %>
    <div>
      <h5><%= climber_education.education.abbreviation %></h5>
      <h5><%= climber_education.year %></h5>
      <h5><%= link_to raw("#{climber_education.education_leader.first_name} #{climber_education.education_leader.last_name}"), climb_leader_profile_path(climber_education.education_leader) %></h5>
    </div>
    <% end %>
  </section>
  <div class="general-spacing"></div>

</div>