config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: 'pages#index'

  get 'pages/index'
  get 'pages/test', as: 'test'

  post 'payments/stripe', to: 'payments#stripe'
  get 'payments/stripe', to: 'payments#stripe', as: 'payments'

  resources :climb_classes,
            :climb_schedules,
            :climb_tags,
            :climbs,
            :climber_educations,
            :climber_experiences,
            :climb_leader_profiles,
            :educations,
            :general_dates,
            :routes,
            :specific_dates,
            :user_roles

post 'users/start_subscription', to: 'users#start_subscription', as: 'subscribe'
post 'users/end_autorenew', to: 'users#end_autorenew', as: 'end_autorenew'
post 'users/restart_autorenew', to: 'users#restart_autorenew', as: 'restart_autorenew'

resources :users do
  resources :climbs do
    resources :climb_apps
  end
end

resources :mountains do
  resources :climbs
end

resources :users do
  resources :climb_apps
  resources :climber_profiles
end

end

app/models/climb_app.rb
class ClimbApp < ActiveRecord::Base
  belongs_to  :user
  belongs_to :climb
end

app/controllers/climb_apps_controller.rb
class ClimbAppsController < ApplicationController
  before_action :set_climb_app, only: [:show, :edit, :update, :destroy]

  # GET /climb_apps
  # GET /climb_apps.json
  def index
    @climb_apps = ClimbApp.where(user_id: current_user.id)
  end

  # GET /climb_apps/1
  # GET /climb_apps/1.json
  def show
  end

  # GET /climb_apps/new
  def new
    # @climb_app = ClimbApp.new
  end

  # GET /climb_apps/1/edit
  def edit
  end

  # POST /climb_apps
  # POST /climb_apps.json
  def create
    @climb_app = ClimbApp.new(climb_app_params)

    respond_to do |format|
      if @climb_app.save
        format.html { redirect_to @climb_app, notice: 'ClimbApp was successfully created.' }
        format.json { render :show, status: :created, location: @climb_app }
      else
        format.html { render :new }
        format.json { render json: @climb_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /climb_apps/1
  # PATCH/PUT /climb_apps/1.json
  def update
    respond_to do |format|
      if @climb_app.update(climb_app_params)
        format.html { redirect_to @climb_app, notice: 'ClimbApp was successfully updated.' }
        format.json { render :show, status: :ok, location: @climb_app }
      else
        format.html { render :edit }
        format.json { render json: @climb_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climb_apps/1
  # DELETE /climb_apps/1.json
  def destroy
    @climb_app.destroy
    respond_to do |format|
      format.html { redirect_to climb_apps_url, notice: 'ClimbApp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_climb_app
      @climb_app = ClimbApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def climb_app_params
      params.fetch(:climb_app, {})
    end
end

app/helpers/climb_apps_helper.rb
module ClimbAppsHelper
end

app/views/climb_apps/_form.html.erb
<%= form_for(@climb_app) do |f| %>
  <% if @climb_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@climb_app.errors.count, "error") %> prohibited this climb_app from being saved:</h2>

      <ul>
      <% @climb_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/climb_apps/edit.html.erb
<h1>Editing ClimbApp</h1>

<%= render 'form' %>

<%= link_to 'Show', @climb_app %> |
<%= link_to 'Back', climb_apps_path %>

app/views/climb_apps/index.html.erb
<h4 id="notice" class="f3"><%= notice %></h4>

<h1>Listing ClimbApps</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @climb_apps.each do |climb_app| %>
      <tr>
        <td><%= climb_app.climb.mountain.name %></td>
        <td><%= climb_app.id  %></td>
        <td><%= climb_app.climb_app_status  %></td>
        <td><%= link_to "Edit", edit_user_climb_app_path(current_user, climb_app) %></td>
        <td><%= link_to 'Destroy', user_climb_app_path(current_user, climb_app), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/climb_apps/new.html.erb
<h1>New ClimbApp</h1>

<%= render 'form' %>

<%= link_to 'Back', climb_apps_path %>

app/views/climb_apps/show.html.erb
<h4 id="notice" class="f3"><%= notice %></h4>

<%= link_to 'Edit', edit_user_climb_app_path(current_user, @climb_app) %> |
<%= link_to 'Back', user_climb_apps_path(current_user) %>